### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by seivazi** [pantor/learning-shifting-for-grasping#1]
Hi @pantor 
Thank you for sharing your great works.
Could you add a License to your current project with Robotic Manipulation projects, similar to your previous project a MIT/BSD make it easier for others to contribute.

Cheers,

**Comment by pantor** [comment]
I've now applied the GPL-3.0 license. Does that fit your needs as well?

**Comment by seivazi** [comment]
Thank you! This is good to work on the code for sure. 

I highly recommend BSD or MIT family license to get more support from industry contributors.
With BSD you make sure industry will use whole project in a iterative manner so they always come back here with new ideas, issues, and solution :)

Here is one example:
https://github.com/dougsm/mvp_grasp

Looking forward to start with the cod!

**Comment by pantor** [comment]
Perfect, I will look into the BSD license later.
