### ISSUE TITLE
Realsense camera

### ISSUE THREAD

**Issue by seivazi** [pantor/learning-shifting-for-grasping#2]
In some of your projects you seems to use realsense camera (e.g. https://github.com/pantor/learning-pick-and-place) but not here. 
Is there any particular reason you prefer Ensenso over Realsense?
I don't know how much a Ensenso cost but I assume it is an expensive camera, do you know how much does it cost?

Cheers,

**Comment by pantor** [comment]
Just for closing this issue: The Ensenso N10 is around 5000€. The Ensenso has depth information of much higher quality and more importantly, has an indstrial grade realibatily. In our experiments, we've a lot of issues with RealSense connection realibility, which is really annoying for large-scale real-world experiments.
